import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/

class FigmaToCodeApp extends StatefulWidget {
const FigmaToCodeApp({super.key});
State<FigmaToCodeApp> createState() => _FigmaToCodeAppState();

}

class _FigmaToCodeAppState extends State<FigmaToCodeApp> {
  //const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(239, 235, 231, 231),
      ),
      home: Scaffold(
        body: ListView(children: const [
          LoginPage(),
        ]),
      ),
    );
  }
}
//********************StatefulWidget******************************/
class LoginPage extends StatefulWidget {
const LoginPage({super.key});
State<LoginPage> createState() => _LoginPageState();


}

class _LoginPageState extends State<LoginPage> {
  //const _LoginPageState({super.key});

bool _obscureText = true;


  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 600,
          margin: EdgeInsets.only(top: 5),
          //clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
            
          ),
          child: Stack(
            children: [
              const Positioned(
                left: 142,
                top: 71,
                
                child: Text(
                
                  'Login',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF75CAF5),
                    fontSize: 26,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              const Positioned(
                left: 78,
                top: 102,
                child: Text(
                  'please fill the input below here',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFFCCC5C5),
                    fontSize: 14,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              






//phone number


              Positioned(
                left: 34,
                top: 144,
                child: SizedBox(
                  width: 298,
                  height: 51,
                  child: Column(
                    children: [
                     

                      Positioned(
                        left: 5,
                        top: 0,
                        child: TextField(
                          enabled: true,

                          style: TextStyle(color:Colors.black), //color of typing
                          cursorColor: Color(0xFF75CAF5),        //color of cursor
                          
                          decoration: InputDecoration
                          (
                            
                            labelText:'Phone number',
                             labelStyle: TextStyle(
                            color: Color(0xFF75CAF5),
                            fontSize: 13,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                            height: 0,
                                 ),


                            prefixIcon  : const Icon(Icons.phone,),
                            prefixIconColor: Colors.black,
                            border: OutlineInputBorder(
                             
                            borderRadius: BorderRadius.circular(5),
                            
                             ),
                            
                            focusedBorder:OutlineInputBorder(
                              borderSide: BorderSide(color: const Color.fromARGB(219, 30, 29, 29),)
                              ),                                
                                 enabledBorder:OutlineInputBorder(
                              borderSide: BorderSide(color: const Color.fromARGB(219, 30, 29, 29),)
                              ),
                               
                          
                          ),
                        ),
                      ),
                     
                    ],
                  ),
                ),
              ),





//password







              Positioned(
                left: 36,
                top: 224,
                child: SizedBox(
                  width: 298,
                  height: 51,
                  child: Column(
                    children: [
                      
                      Positioned(
                        left: 3,
                        top: 0,
                        child: TextField(
                          enabled: true,

                          style: TextStyle(color:Colors.black), //color of typing
                          cursorColor: Color(0xFF75CAF5),        //color of cursor




                          obscureText: _obscureText,

                          decoration: InputDecoration
                          (

                          
                          labelText: 'Password ',
                        
                          labelStyle: const TextStyle(
                            color: Color(0xFF75CAF5),
                            fontSize: 13,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                            height: 0,
                             ),


                             prefixIcon  : IconButton(icon: Icon(_obscureText ? Icons.visibility : Icons.visibility_off,),
                                    onPressed: () {
                                      setState(() {
                                        _obscureText = !_obscureText;
                                      });
                                    },
                                  ),
                                  
                                  prefixIconColor: Colors.black,
                            border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(5),
                            
                             ),
                             focusedBorder:OutlineInputBorder(
                              borderSide: BorderSide(color: const Color.fromARGB(219, 30, 29, 29))
                              ),
                                   

                                   enabledBorder:OutlineInputBorder(
                              borderSide: BorderSide(color: const Color.fromARGB(219, 30, 29, 29),)
                              ),

                             
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),

                    //button
              Positioned(
                left: 42,
                top: 359,
                child: SizedBox(
                   width: 600,
                    height: 60,
                  child: Stack(
                    children: [
                     
                     Positioned(
                        left: 3,
                        top: 7,
                        child: SizedBox(
                          width: 274,
                          height: 45,
                          
                          child: MaterialButton(
                            
                            child: const Text('Login'),
                             color: const Color(0xFF322E9F),
                              textColor: Colors.white,
                              
                              padding: EdgeInsets.symmetric(horizontal: 30,vertical: 19),                              onPressed: ()
                                {
                                 
                                },
                                
                              shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                               ),

                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),

//last line

               Positioned(
                left: 77,
                top: 555,

              child:  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      const Text('Don\'t have an account',    //----------------true
                      style: TextStyle(
                        color: Color.fromARGB(255, 28, 28, 28),
                        fontWeight: FontWeight.bold,
                        
                     ),
                      ),
                      TextButton(
                        onPressed: () {
                          /*Navigator.pushReplacement(
                            context,
                            MaterialPageRoute(
                              builder: (context) =>
                                  const RegisterPage(title: 'Register UI'),
                            ),
                          );*/
                        },
                       
                        
                        
                        child:  Text('Sign up',
                        style: TextStyle(
                        color: Color.fromARGB(255, 17, 171, 209),
                        fontWeight: FontWeight.bold,
                        
                     ),
                      ),
                      ),
                    ],
                  ),
               ),



            ],
          ),
        ),
      ],
    );
  }
}

